#!/bin/bash

PATTERN="\(201[67][0-9]\{4\}\_[0-9][0-9]_[A-Z][0-9]\).*"


exe="/groups/saalfeld/home/bogovicj/dev/template/template-building-pub/scripts/visSliceClahe"

out_dir="/groups/saalfeld/home/bogovicj/pubDrafts/grpDrosTemplate/grpDrosTemplate/figs/regExamplesArrow";

## JRC2018
#img_list="/groups/saalfeld/home/bogovicj/dev/template/template-building-pub/scripts/visualization/jrc18_img_list.txt"
#z="z139 z174 z255"

# JFRC2010
#img_list="/groups/saalfeld/home/bogovicj/dev/template/template-building-pub/scripts/visualization/jfrc2010_img_list.txt"
#z="z74 z105 z169"

## JFRC2013
#img_list="/groups/saalfeld/home/bogovicj/dev/template/template-building-pub/scripts/visualization/jfrc2013_img_list.txt"
#z="z115 z154 z221"

## FCWB 
img_list="/groups/saalfeld/home/bogovicj/dev/template/template-building-pub/scripts/visualization/fcwb_img_list.txt"
z="z41 z55 z80"

## Tefor
#img_list="/groups/saalfeld/home/bogovicj/dev/template/template-building-pub/scripts/visualization/tefor_img_list.txt"
#z="z71 z89 z138"


minmax="0 900"

for f in `cat $img_list`
do
    echo $f
    d="${f%/*}" 
    prefix=`echo "$f" | sed "s/.*$PATTERN/\1/g"`
    
    tmp=$(echo $d | sed 's:/nrs/saalfeld/john/projects/flyChemStainAtlas/all_evals/::g')
    tmp2="${tmp#*/}"

    template=${tmp%%/*}
    alg=${tmp2%/*}

    #echo "tmp : $tmp"
    #echo "tmp2: $tmp2"

    echo "$prefix"
    echo "$template"
    echo "$alg"

    out="${out_dir}/${template}_${alg}_${prefix}"
    echo $out

    $exe "$f" "$out" $minmax $z

    echo " "
    #break
done

