#!/bin/bash

BASEDIR="/nrs/saalfeld/john/projects/flyChemStainAtlas/all_evals"

#dir_list="\
#    JFRCtemplate2010/antsRegDog JFRCtemplate2010/antsRegOwl JFRCtemplate2010/antsRegYang JFRCtemplate2010/cmtkCOG JFRCtemplate2010/cmtkCow JFRCtemplate2010/cmtkHideo \
#    JFRC2013_lo/antsRegDog JFRC2013_lo/antsRegOwl JFRC2013_lo/antsRegYang JFRC2013_lo/cmtkCOG JFRC2013_lo/cmtkCow JFRC2013_lo/cmtkHideo \
#    TeforBrain_f/antsRegDog TeforBrain_f/antsRegOwl TeforBrain_f/antsRegYang TeforBrain_f/cmtkCOG TeforBrain_f/cmtkCow TeforBrain_f/cmtkHideo \
#    F-antsFlip_lo/antsRegDog F-antsFlip_lo/antsRegOwl F-antsFlip_lo/antsRegYang F-antsFlip_lo/cmtkCOG F-antsFlip_lo/cmtkCow F-antsFlip_lo/cmtkHideo \
#    F-cmtkFlip_lof/antsRegDog F-cmtkFlip_lof/antsRegOwl F-cmtkFlip_lof/antsRegYang F-cmtkFlip_lof/cmtkCOG F-cmtkFlip_lof/cmtkCow F-cmtkFlip_lof/cmtkHideo \
#    indvs/C3_def/antsRegDog8 indvs/C3_def/antsRegOwl indvs/C3_def/antsRegYang indvs/C3_def/cmtkCOG indvs/C3_def/cmtkCow indvs/C3_def/cmtkHideo \
#    indvs/D1_def/antsRegDog8 indvs/D1_def/antsRegOwl indvs/D1_def/antsRegYang indvs/D1_def/cmtkCOG indvs/D1_def/cmtkCow indvs/D1_def/cmtkHideo"

dir_list="\
    indvs/C3_def/antsRegDog8 indvs/C3_def/antsRegOwl indvs/C3_def/antsRegYang indvs/C3_def/cmtkCOG indvs/C3_def/cmtkCow indvs/C3_def/cmtkHideo \
    indvs/D1_def/antsRegDog8 indvs/D1_def/antsRegOwl indvs/D1_def/antsRegYang indvs/D1_def/cmtkCOG indvs/D1_def/cmtkCow indvs/D1_def/cmtkHideo"


#line=3


TABLE_FILE="/nrs/saalfeld/john/projects/flyChemStainAtlas/all_evals/time_mem_data.csv"

for d in $dir_list;
do

    echo $d

    dest_file="${BASEDIR}/${d}/timeMemStats.csv"
    echo "DEST FILE $dest_file"

    prefix=$(echo $d | sed -e 's:indvs/::g' -e 's:/:,:g')
    echo "${prefix}"

    N=$(ls -U ${BASEDIR}/${d}/*sh.o* | wc -l)
    echo "N: $N"

    if [[ $N != 20 ]];
    then
        echo "Expect exactly 20 outputs, but found $N, skipping"
        continue
    fi

    #parseRunTimes $dest_file `ls ${BASEDIR}/${d}/*sh.o*` 
     
    sed "s/^/${prefix},/g" $dest_file >> $TABLE_FILE

    echo " "
done

echo " "
echo " "

