#!/bin/bash
# Cmtk parameters from Hideo

script="/groups/saalfeld/home/bogovicj/dev/jefferislab/AnalysisSuiteBin/munger.pl"
bindir="/misc/local/cmtk-3.1.0/lib/cmtk/bin"

moving="$1"
target="$2"
output="$3"

nThreads="4"

$script -b "$bindir" -e nii -v -a -w \
    -X 26 -C 8 -G 80 -R 4 \
    -A '--accuracy 0.8' -W '--accuracy 2' \
    -T $nThreads \
    -s $target $moving
