#!/bin/bash
# Cmtk parameters from Cachero, Ostrovsky 2010
# http://flybrain.mrc-lmb.cam.ac.uk/dokuwiki/doku.php?id=warping_manual:registration_gui

script="/groups/saalfeld/home/bogovicj/dev/jefferislab/AnalysisSuiteBin/munger.pl"
bindir="/misc/local/cmtk-3.1.0/lib/cmtk/bin"

moving="$1"
target="$2"
output="$3"

nThreads="4"

$script -b "$bindir" -e nii -v -aw -X 26 -C 8 -G 80 -R 4 \
    -A '--accuracy 0.4' -W '--accuracy 0.4' -T $nThreads -s \
    $target $moving
