#!/bin/bash
# Detects what iteration was last completed for buildtemplateparallel

TRANSFORM="$1"
i=0
while true;
do
    #echo $i 
    if [ -d ${TRANSFORM}_iteration_$i ];
    then
        ((i++))
    else
        break
    fi
done
echo $i
