#!/bin/bash

# Needs environment variables: 
#   CMTKBINDIR: directory with cmtk executables 
#   MUNGERDIR: directory with munger.pl
# 
# where munger.pl is from this github 
#   github.com/jefferis/AnalysisSuiteBin 


script="${MUNGERDIR}/munger.pl"

moving="$1"
target="$2"
output="$3"

nThreads="4"

$script -b "$CMTKBINDIR" -e nii -v -aw -X 26 -C 8 -G 80 -E 5e-1 -R 4 \
    -A '--accuracy 1.6' -W '--accuracy 1.6' -T $nThreads -s \
    $target $moving
