#!/bin/bash
# Cmtk parameters from Cachero, Ostrovsky 2010
# http://flybrain.mrc-lmb.cam.ac.uk/dokuwiki/doku.php?id=warping_manual:registration_gui

# Needs environment variables: 
#   CMTKBINDIR: directory with cmtk executables 
#   MUNGERDIR: directory with munger.pl
# 
# where munger.pl is from this github 
#   github.com/jefferis/AnalysisSuiteBin 


script="${MUNGERDIR}/munger.pl"

moving="$1"
target="$2"
output="$3"

nThreads="4"

$script -b "$CMTKBINDIR" -e nii -v -aw -X 26 -C 8 -G 80 -R 4 \
    -A '--accuracy 0.4' -W '--accuracy 0.4' -T $nThreads -s \
    $target $moving
