#!/bin/bash

input="$1"
if [[ "$input" == *gz ]]
then
#    echo "is gzipped"
    gunzip -c $input | head -n 12 > tmp
else
#    echo "not gzipped"
    head -n 12 $input > tmp
fi
echo '}' >> tmp
 
#dof2mat --transpose tmp | tr '\n' '\t' | sed -e 's/\t\t/,/g' -e 's/\t/,/g' -e 's/,$/\n/g'
dof2mat tmp | tr '\n' '\t' | sed -e 's/\t\t/,/g' -e 's/\t/,/g' -e 's/,$/\n/g'

rm tmp

