#!/bin/bash

input="$1"
center="$2"

tmpfile=${input}_tmp

if [[ "$input" == *gz ]]
then
    gunzip -c $input | head -n 12 > $tmpfile
else
    head -n 12 $input > $tmpfile
fi
echo '}' >> $tmpfile
 
paramsImglib=$(dof2mat --transpose $tmpfile | tr '\n' '\t' | sed -e 's/\t\t/,/g' -e 's/\t/,/g' -e 's/,$/\n/g')
params=$(echo $paramsImglib | awk -F, 'BEGIN {OFS=","} {print $1,$2,$3, $5,$6,$7, $9,$10,$11, $4,$8,$12 }')

centerAffine $params $center

rm $tmpfile
