#!/bin/bash

posFieldX="$1" # must be nii (or nrrd?)
posFieldY="$2" # must be nii
posFieldZ="$3" # must be nii
ref="$4"
reg="$5"
out="$6"

export CMTK_WRITE_UNCOMPRESSED=1
# Deform the coordinate images
reformatx -o ${out}-x.nii --floating $posFieldX $ref $reg
reformatx -o ${out}-y.nii --floating $posFieldY $ref $reg
reformatx -o ${out}-z.nii --floating $posFieldZ $ref $reg
unset CMTK_WRITE_UNCOMPRESSED

# Convert position fields to displacement field
position2Displacement --x ${out}-pos ${out}-x.nii
position2Displacement --y ${out}-pos ${out}-y.nii 
position2Displacement --z ${out}-pos ${out}-z.nii 

# Convert to nii
resaveVolumeMipav ${out}-pos-x.tif ${out}-pos-x.nii
resaveVolumeMipav ${out}-pos-y.tif ${out}-pos-y.nii
resaveVolumeMipav ${out}-pos-z.tif ${out}-pos-z.nii

CreateDisplacementField 3 0 ${out}-pos-x.nii ${out}-pos-y.nii ${out}-pos-z.nii ${out}.nii

## cleanup
#rm -v ${out}-x.nii
#rm -v ${out}-y.nii
#rm -v ${out}-z.nii
#rm -v ${out}.tif
