#!/bin/bash
# Usage:
#   convertAffine <input affine file> <output affine file>

javaOpts="-Xmx1g"

BASEDIR=$(dirname "$0")
cp=`cat "$BASEDIR/classpath.cp"`

# If the output is xform (cmtk's format),
# first convert to a 4d matrix, then use cmtks mat2dof
if [[ $2 == *xform ]]
then
    echo 'yes'
    tmp="$(mktemp).mat"
    java -cp "$cp" $javaOpts io.ConvertAffine -i $1 -o $tmp
    mat2CmtkXform $tmp > $2
    rm $tmp
else
    java -cp "$cp" $javaOpts io.ConvertAffine $@
fi
