#!/bin/bash
# Computes the pairwise distance between two skeletons
# Takes as input:
#   two skeletons 
#   two distance transform images
#   one compartment label image
#


PATTERN="^\(2016[0-9]\{4\}\_[0-9][0-9]_[A-Z][0-9]\).*"
DELETEPATTERN="_Scope_.*"

dir=`pwd`

im1="$1"
im2="$2"
dist_im1="$3"
dist_im2="$4"
compartments="$5"
suffix="$7"

name1="${dist_im1##*/}"
name2="${dist_im2##*/}"

prefix1=`echo "$name1" | sed "s/$DELETEPATTERN//g"`
prefix2=`echo "$name2" | sed "s/$DELETEPATTERN//g"`
echo "prefix1 $prefix1"
echo "prefix2 $prefix2"

# "Forward" direction
echo "hist forward"
h1="${dir}/${prefix1}-${prefix2}_${suffix}_labelData"
compartmentImageData $h1 $dist_im1 $compartments $im2 "false"

# "Reverse" direction
echo "hist reverse"
h2="${dir}/${prefix2}-${prefix1}_${suffix}_labelData"
compartmentImageData $h2 $dist_im2 $compartments $im1 "false"
