#!/bin/bash
# Arguments:
#   -i input
#   -o output
#   -f factors (should be greater than 1)
#   -j threads
#   -p interp
#   -s sourceSigmas
#   -t targetSigmas

javaOpts="-Xmx96g"
if [[ $1 == '-j' ]];
then
    shift
    javaOpts="$1"
    shift
fi

BASEDIR=$(dirname "$0")
cp=`cat "$BASEDIR/theclasspath.cp"`
java -cp "$cp" $javaOpts process.DownsampleGaussian "$@"
