#!/bin/bash
# 

GZPATTERN="*.gz"
PATTERN=".*\(201[6-7][0-9]\{4\}\_[0-9][0-9]_[A-Z][0-9]\).*"

neuronList="/nrs/saalfeld/john/projects/flyChemStainAtlas/eval/dataNew/neuron_list.txt"

HISTBINS="128"
HISTTHRESH="0.5"

HISTMIN="-2"
HISTMAX="4"

LOGHISTMIN="-2"
LOGHISTMAX="2" 

ref="$1"
if [[ -z $ref ]];
then
    echo "Must specify reference" 
    exit 1
fi

compartments="$2"

isCmtk=""
if [[ -d Registration ]];
then
    echo "is CMTK"
    isCmtk="1"
fi

isElastix=""
numElastix=$(ls */elastix.log | wc -l)
if [[ $numElastix > 0 ]];
then
    isElastix="1"
fi

mkdir -p jacobian

dir=`pwd`
i=0

while read neurImg
do
    echo $neurImg

    job="jacobian/jacobian_$i.sh"
    echo "#!/bin/bash" > $job
     
    if [[ -n $isCmtk ]];
    then
        regXfms=`matchEvalDataCmtk $neurImg $dir`
        echo "regXfms: $regXfms"
        field=$regXfms
    elif [[ -n $isElastix ]];
    then
        regXfms=`matchEvalDataElastix $neurImg $dir`
        echo "regXfms: $regXfms"
        field=$regXfms
    else
        regXfms=`matchEvalData $neurImg $dir`
        field=$(echo $regXfms | awk '{print $2}')   
    fi
    echo "field: $field"

    #if [[ -f "$dir/jacobian/${out}jacobian.nii" ]];
    #then
    #    echo "skipping $out"
    #else

        if [[ $isCmtk ]];
        then
            echo "editing name for Elastix"
            #echo "field: $field"

            tmp=$(dirname $field)

            prefix=$(echo $tmp | sed "s/$PATTERN/\1/g")
            #echo "prefix: $prefix"

            out="${prefix}_xform"

            if [ -f $out ]; then
                echo "Exists, skipping $out"
                continue
            fi
            echo "out: $out"

            echo "field: $field"
            if [[ $field == *.gz ]];
            then 
                #echo "stripping off gz"
                field=${field%.*}
            fi
            echo "field: $field"


            jacimg="$dir/jacobian/${out}jacobian.nii"
            jacimgzip="$dir/jacobian/${out}jacobian.nii.gz"
            jacimgr="$dir/jacobian/${out}jacobian_resamp.nii"

            echo "reformatx --jacobian-correct-global -o $jacimg $ref -j $field" >> $job
            echo "gunzip -v $jacimgzip" >> $job
            echo "ResampleImageBySpacing 3 $jacimg $jacimgr 0.5 0.5 0.5 0 0 0" >> $job
            echo " "

        elif [[ -n $isElastix ]];
        then

            echo "editing name for Cmtk"
            tmp=$(dirname $field)

            prefix=$(echo $tmp | sed "s/$PATTERN/\1/g")

            out="${prefix}_xform"
            if [ -f $out ]; then
                echo "Exists, skipping $out"
                continue
            fi
            echo "out: $out"

            echo "field: $field"
            if [[ $field == *.gz ]];
            then 
                #echo "stripping off gz"
                field=${field%.*}
            fi
            echo "field: $field"


            jacimg="$dir/jacobian/${out}jacobian.nrrd"
            jacimgzip="$dir/jacobian/${out}jacobian.nrrd"
            jacimgr="$dir/jacobian/${out}jacobian_resamp.nrrd"

            echo "reformatx --jacobian-correct-global -o $jacimg $ref -j $field" >> $job
            echo "gunzip -v $jacimgzip" >> $job
            echo "ResampleImageBySpacing 3 $jacimg $jacimgr 0.5 0.5 0.5 0 0 0" >> $job
            echo " "

        else
            baseName=${field##*/}

            out=`echo $baseName | sed 's/.nii//g'`
            if [ -f $out ]; then
                echo "Exists, skipping $out"
                continue
            fi
            echo "out: $out"

            jacimg="$dir/jacobian/${out}jacobian.nii"
            jacimgzip="$dir/jacobian/${out}jacobian.nii.gz"
            jacimgr="$dir/jacobian/${out}jacobian_resamp.nii"

            echo "#!/bin/bash" > $job
            ##echo "ANTSJacobian 3 $field $dir/jacobian/$out 0" >> $job
            ##echo "ANTSJacobian 3 $field $dir/jacobian/$out 1" >> $job # log jacobian
            ##echo "gunzip -v $dir/jacobian/${out}logjacobian.nii.gz" >> $job

            echo "CreateJacobianDeterminantImage 3 $field $jacimg 0 0" >> $job

            ## Transform to 0.5um isotropic
            echo "ResampleImageBySpacing 3 $jacimg $jacimgr 0.5 0.5 0.5 0 0 0" >> $job
        fi

    #fi
    
    ## Dump data
    ## This is quite slow and very memory hungry
    ## Faster alternative Below
    #data_out="$dir/jacobian/${out}_data.csv"
    #echo "compartmentImageData $data_out $jacimgr $compartments $compartments false" >> $job
    #echo "jacLabelStats $data_out" >> $job

    chmod +x "$job"

    ((i++))
    #break

done <$neuronList

cd jacobian
subJobs -w -o '-n 4' jacobian*sh

## This approach is much faster if only the mean and variance are needed
## Uses an online algorithm to estimate those two quantities in one
## pass through the data
stats_out="$dir/jacobian/stats.csv"
jacInputs=$(readlink -f *resamp* | sed 's/^/-i /g' | tr '\n' ' ')

jacstatsjob="stats_job.sh"
echo "#!/bin/bash" > $jacstatsjob
echo "labelStats -o $stats_out -a "-1" -l $compartments $jacInputs" >> $jacstatsjob
chmod +x $jacstatsjob

./$jacstatsjob

cd ..
