#!/bin/bash

host="$1"
cmd="$2"

thisdir=`pwd`
cdcmd="cd $thisdir"

echo "host: $host"
echo "cmd: $cmd"

ssh -t $host << EOF
    $cdcmd

    pwd # print current directory if we want to
    $cmd 

    bash -l
EOF
