#!/bin/bash
# Find scripts that failed (that don't have output)

prefixPattern="s:.*\(201[6-7][0-9]\{4\}\_[0-9][0-9]_[A-Z][0-9]\).*:\1:g"

isCmtk=""
if [[ -d Registration ]];
then
    echo "is CMTK"
    isCmtk="1"
fi

if [[ -n $isCmtk ]];
then
    echo "is CMTK" 
    # Find directories that DO NOT have a file 'registration.gz' in it
    res=$(find Registration/warp -mindepth 1 -maxdepth 1 -type d '!' -exec test -e "{}/registration.gz" ';' -print | sed 's:Registration/warp/::g' | sed "$prefixPattern")
    for r in $res; do
        grep -l $r *sh
    done
else
    echo "not CMTK, not yet implemented"
fi
