#!/bin/bash

template="/groups/saalfeld/home/bogovicj/dev/template/template-building/scripts/expSummaryTemplate.tex"
cp $template .


loss="loss.png"
L0H=`ls combined_hist_line0.png`
LL0H=`ls combined_hist_line0-logy.png`

L1H=`ls combined_hist_line1.png`
LL1H=`ls combined_hist_line1-logy.png`

L2H=`ls combined_hist_line2.png`
LL2H=`ls combined_hist_line2-logy.png`

L3H=`ls combined_hist_line3.png`
LL3H=`ls combined_hist_line3-logy.png`


finalSummaryFile=summary.tex

sed -e "s/%L0H/$L0H/g" -e "s/%LL0H/$LL0H/g" \
    -e "s/%L1H/$L1H/g" -e "s/%LL1H/$LL1H/g" \
    -e "s/%L2H/$L2H/g" -e "s/%LL2H/$LL2H/g" \
    -e "s/%L3H/$L3H/g" -e "s/%LL3H/$LL3H/g" \
    expSummaryTemplate.tex > "$finalSummaryFile"

pdflatex "$finalSummaryFile"
