#!/bin/bash
#
# Usage: 
#   cmtkParams2Xform 

function printXform {

    echo "    affine_xform {" 
    echo "       xlate $1 $2 $3" 
    echo "       rotate $4 $5 $6" 
    echo "       scale $7 $8 $9" 
    echo "       shear $10 $11 $12" 
    echo "       center $13 $14 $15" 
    echo "    }
}

params=$(mat2dof < $1 | awk '{print $2}' | paste -sd ' ')

printXform $params
