#!/bin/bash
#
# Usage: 
#   cmtkParams2Xform 

function printXform {
    echo "! TYPEDSTREAM 2.4"
    echo ""
    echo "registration {" 
    echo "    affine_xform {" 
    echo "       xlate $1 $2 $3" 
    echo "       rotate $4 $5 $6" 
    echo "       scale $7 $8 $9" 
    echo "       shear ${10} ${11} ${12}" 
    echo "       center ${13} ${14} ${15}" 
    echo "    }"
    echo "}"
}

# use temporary file to store transpose
tmp=$(mktemp)
transpose $1 > $tmp

params=$(mat2dof < $tmp | awk '{print $2}' | paste -sd ' ')

rm $tmp

printXform $params
