#!/bin/bash
# Returns the affine and deformable ants transforms for the input
# subject.  Finds the correct files by matching the file prefix


#REGDIR="/nrs/saalfeld/john/projects/flyChemStainAtlas/eval/data"

in="$1"
REGDIR="$2"

if [[ -f $in ]];
then
#    echo "is a file"
    input=${in##*/}  
else
    input="$in"
fi

pattern="^\(201[6-7][0-9]\{4\}\_[0-9][0-9]_[A-Z][0-9]\).*"

#echo "$input"
prefix=`echo "$input" | sed "s/$pattern/\1/g"`
#echo $prefix

affine=`ls ${REGDIR}/$prefix*Affine.mat`
deformation=`ls ${REGDIR}/$prefix*Warp.nii | grep -v 'InverseWarp'`

echo "$affine $deformation"
