#!/bin/bash


#REGDIR="/nrs/saalfeld/john/projects/flyChemStainAtlas/eval/data"

in="$1"
pattern="^\(2016[0-9]\{4\}\_[0-9][0-9]_[A-Z][0-9]\).*"
REGDIR="$2"

prefix=`echo "$in" | sed "s/$pattern/\1/g"`
#echo $prefix

affine=`ls ${REGDIR}/$prefix*Affine.mat`
deformation=`ls ${REGDIR}/$prefix*Warp.nii`

echo "$affine $deformation"
