#!/bin/bash
# Usage:
#   meanVar <nThreads> <outputPrefix> <Files...>

BASEDIR=$(dirname "$0")
cp=`cat "$BASEDIR/theclasspath.cp"`

nThreads="$1"
shift
out="$1"
shift

args=""
for f in $@
do
    path=`readlink -f $f`
    args="$args $path" 
done
echo $args

/misc/local/jdk1.8.0_102/bin/java -cp "$cp" -Xmx92g process.PerPixelMeanVariance $nThreads $out $args
