#!/bin/bash
# Returns the line, 

PAIRLIST="/nrs/saalfeld/john/projects/flyChemStainAtlas/eval/prefix_list_by_neuron.txt"
PATTERN="^\(201[67][0-9]\{4\}\_[0-9][0-9]_[A-Z][0-9]\).*"

in1="$1"

#Strip off the path
name1="${in1##*/}"
prefix1=`echo "$name1" | sed "s/$PATTERN/\1/g"`

line=`grep -n $prefix1 $PAIRLIST`
res=${line%:*}
res0=$(($res-1))
echo $res0
