#!/bin/bash
# Arguments:
#   -i input
#   -o output
#   -x pad amount in pixels
#   -p pad amount in physical units
#   --java <java options>

javaOpts="-Xmx240g"
if [[ $1 == '--java' ]];
then
    shift
    javaOpts="$1"
    shift
fi

BASEDIR=$(dirname "$0")
cp=`cat "$BASEDIR/gaussDs.cp"`
java -cp "$cp" $javaOpts process.Pad "$@"
