#!/bin/bash
# Returns the field of view of the input nrrd in pixel units

nrrdFile="$1"

min="0,0,0"
max=$(unu head $nrrdFile | grep sizes | sed 's/sizes: //g' | awk 'BEGIN {OFS=","}{print $1-1,$2-1,$3-1}')

echo ${min}:${max}
