#!/bin/bash
# Returns the field of view of the input nrrd in pixel units

nrrdFile="$1"
dim=$(unu head $nrrdFile | grep dimension | sed 's/dimension: //g')

min="0,0,0"
if [[ $dim == 4 ]];
then
    max=$( unu head $nrrdFile| grep sizes | sed 's/sizes: //g' | awk 'BEGIN {OFS=","}{print $2-1,$3-1,$4-1}')
else
    max=$( unu head $nrrdFile| grep sizes | sed 's/sizes: //g' | awk 'BEGIN {OFS=","}{print $1-1,$2-1,$3-1}')
fi

echo ${min}:${max}
