#!/bin/bash
#
# Run like this:
#   parseRunTimesElastix <dir_pattern> > times.csv 

dir_pattern="$1"
# Converts XmYs to seconds
grep -h 'Total time elapsed:' $dir_pattern/elastix.log | awk -F: '{print $2}' | sed -e 's/[hm]/,/g' -e 's/s//g' | awk -F, '{print 60*$1 + $2}'

