#!/bin/bash
# Do post processing on registration

POSFIELDX="/nrs/saalfeld/john/projects/flyChemStainAtlas/posFields/pfx_850-650-250.nii"
POSFIELDY="/nrs/saalfeld/john/projects/flyChemStainAtlas/posFields/pfy_850-650-250.nii"
POSFIELDZ="/nrs/saalfeld/john/projects/flyChemStainAtlas/posFields/pfz_850-650-250.nii"

TEMPLATE="$1"
INTERVAL="$2"

if [[ -d Registration ]];
then
    echo "is CMTK"
    isCmtk="1"
fi

if [[ -n $isCmtk ]];
then
    #CMTK

    # Skip if we've done this already
    Nreg=`ls Registration/warp/*/registration* | wc -l`
    Nxform=`ls Registration/warp/*/xform.nii | wc -l`

    if [[ $Nreg == $Nxform ]];
    then
        echo "xforms found, returning"
        exit 0
    fi

    qq=`which bsub`
    if [ ${#qq} -lt 1 ] ; then
      #executeRemote 'login2.int.janelia.org' 'bsub -n 4 -o cmtkConv.o%J -e cmtkConv.e%J ''runConvertCmtkWarps -w'''
      echo "CONVERT CMTK WARPS"
      executeRemote 'login2.int.janelia.org' "runConvertCmtkWarps -w -r $TEMPLATE"
    else
      echo "CONVERT CMTK WARPS"
      bsub -n 4 -o cmtkConv.o%J -e cmtkConv.e%J "runConvertCmtkWarps -w -r $TEMPLATE"
    fi
else
    # ANTS
    warpFiles=`ls *Warp.nii.gz | grep -v Inverse`
    if [[ ! -z "$warpFiles" ]];
    then
        gunzip -v $warpFiles
    else
        echo "  No compressed warps found."
    fi
    affineConv *Affine.txt
fi
