#!/bin/bash

export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=4
echo "THREADS: $ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS"

in="$1"
nc82Img="/groups/saalfeld/public/vfb/JFRCtemplate2010.nrrd"
compartmentImg="/groups/saalfeld/public/vfb/JFRCtempate2010_mask130819_Original.nrrd"

script="/groups/saalfeld/home/bogovicj/libraries/antsbin2/bin/antsIntroductionRegularizedJohn.sh"
moving=$nc82Img
target=$in
output="compartmentReg"
dir=`pwd`
maxiters="15x25x45x10"
metric="CC"
transform="EL"
regularization="Gauss[1.0,1.5]"

mkdir -p compartments
$script -d 3 -r $target -i $moving -o $output -m $maxiters -n 0 \
    -s $metric -t $transform -e $regularization -f 1 

WarpImageMultiTransform 3 $compartmentImg ${output}_labels.nii -R $target ${output}Warp.nii.gz ${output}Affine.txt --use-NN 
ConvertImage 3 ${output}_labels.nii ${output}_labels_uShort.nii 2
