#!/bin/bash
# resample an image to a different resolution

img="$1"
shift
out="$1"
shift
resOut="$1"
shift

if [[ $img =~ *nii ]];
then
    echo "nii"

    intervalIn=$(parseNiiSize $img)
    echo "interval: $intervalIn"

    resIn=$(parseNiiRes $img)
    echo "original image resolution: $resIn"

    intervalOut=$(changeIntervalRes $intervalIn $resIn $resOut) 
    echo "real output resolution: $resOut"

    renderTransformed $img $out $intervalOut -q 8 -r $resOut $@

else
    echo "not nii"
    renderTransformed $img $out "infer" -q 8 -r $resOut $@
fi

