#!/bin/bash

waitScript="/groups/saalfeld/home/bogovicj/dev/template/template-building/scripts/waitForLSFJobs.pl"

neuronList="/nrs/saalfeld/john/projects/flyChemStainAtlas/eval/dataNew/neuron_list.txt"
#intervalOut="0,0,0:1000,700,300"
#intervalOut="0,0,0:799,424,213"

template="$1"
intervalOut=`parseNiiInterval $template`

isCmtk=""
if [[ -d Registration ]];
then
    echo "is CMTK"
    isCmtk="1"
fi

dir=`pwd`
i=0
while read neurImg
do
    echo $neurImg
    xfmList="-i"
    downPattern=`echo "$neurImg" | sed 's/_C2_Neuron.tif/_C1/g'`
    downXfm=`ls $downPattern*down.txt`
    xfmList="$xfmList $downXfm"
     
    if [[ -n $isCmtk ]];
    then
        regXfms=`matchEvalDataCmtk --conv $neurImg $dir`
    else
        regXfms=`matchEvalData $neurImg $dir`
    fi
    xfmList="$xfmList $regXfms"
    echo $xfmList
    
    baseName=${neurImg##*/}
    out=`echo $baseName | sed 's/.tif/_xfm.tif/g'`
    echo $out
      
    job="neuron_xfm_$i.sh"
    echo "#!/bin/bash" > $job
    echo "renderTransformed $neurImg $dir/$out $intervalOut $xfmList -q 4" >> $job
    chmod +x "$job"

    ((i++))
    #break

done <$neuronList


haveBsub=`which bsub`
if [ $haveBsub ]; 
then
    echo "yes bsub: $haveBsub"
    jobIds=""
    for j in `ls neuron_xfm*sh`
    do
        id=`bsub -n 4 -o $j.o%J -e $j.e%J "./$j" | awk '{ gsub("[<>]","",$2); print $2}'`
        jobIds="$jobIds $id"
        sleep 1
    done
    $waitScript 1 60 $jobIds
else
    echo "no bsub"
    submitJobScript="submit_neuron_xfm_jobs.sh"
    echo "#!/bin/bash" > $submitJobScript
    echo 'jobIds=""' >> $submitJobScript
    for j in `ls neuron_xfm*sh`
    do
        bsubcmd="bsub -n 4 -o $j.o%J -e $j.e%J ""./$j"
        awkcmd=' | awk '"'"'{ gsub("[<>]","",$2); print $2}'"'"
        echo "id=\`${bsubcmd}${awkcmd}\`" >> $submitJobScript
        echo 'jobIds="$jobIds $id"' >> $submitJobScript
        echo "sleep 1" >> $submitJobScript
    done
    echo "$waitScript 1 60 "'$jobIds' >> $submitJobScript
    chmod +x $submitJobScript
    executeRemote 'login2.int.janelia.org' "./$submitJobScript"
fi
