#!/bin/bash

#BASEDIR=$(dirname "$0")
#cp=`cat "$BASEDIR/classpath.cp"`
#java -cp "$cp" -Xmx96g -Dspark.master=local[36] process.TransformN5 "$@"

#class="process.SparkTest"


nodes="$1"
shift;

export N_DRIVER_THREADS='2'
export MEMORY_PER_NODE='115'

#jar="/groups/saalfeld/home/bogovicj/dev/template/template-building_n5/target/saalfeldlab-template-building-0.1.2-n5spark-SNAPSHOT-jar-with-dependencies.jar"
jar="/groups/saalfeld/home/bogovicj/dev/template/template-building_n5/jars/saalfeldlab-template-building-0.1.2-n5spark-SNAPSHOT-provided.jar"


class="process.TransformN5"

/groups/saalfeld/home/bogovicj/dev/n5/n5-spark/startup-scripts/spark-janelia/flintstone/flintstone-lsd.sh \
    $nodes \
    $jar \
    $class \
    $@
