#!/bin/bash
# Usage:
#   sym2Canonical <flip-matrix> <affine-registering-flip-to-original> 

BASEDIR=$(dirname "$0")
cp=`cat "$BASEDIR/theclasspath.cp"`
java -cp "$cp" -Xmx36g transforms.PlaneOfSymmetry "$@"
