#!/bin/bash
# Run the entire analysis pipeline

basedir=`pwd`

DOCENTILES=""
DORAYLEIGH=""
DOMEANVAR=""
DOSYMMETRY=""
DOHISTOGRAM=""
DOFLIPVARIANCE=""

ISJFRC2013=""
PREFIX="ALLF"

CENTILE_OPTS="0,0.1,0.5,0.9,1"

while getopts "cjmprst:v" OPT
do
    case $OPT in
    c) # centiles
        DOCENTILES="1"
        ;;
    h) # histograms
        DOHISTOGRAM="1"
        ;;
    j) # using JFRC013template
        ISJFRC2013="1"
        ;;
    m) # mean and variance
        DOMEANVAR="1"
        ;;
    r) # rayleigh
       DORAYLEIGH="1" 
       ;;
    s) # symmetry 
       DOSYMMETRY="1"
       ;;
    p) # prefix 
       PREFIX=$OPTARG
       echo "Prefix: $PREFIX"
       ;;
    t) # template 
       TEMPLATE=$OPTARG
       echo "Found template: $TEMPLATE"
       ;;
    v) # do flip variance 
       DOFLIPVARIANCE="1"
       ;;
    \?) # getopts issues an error message
       echo "$USAGE" >&2
       exit 1
       ;;
    esac
done


flipVarianceScript="qsubFlipVariance"
if [ $ISJFRC2013 ]; then 
    flipVarianceScript="qsubFlipVarianceJFRC2013"
fi
echo "flipVarianceScript: $flipVarianceScript"

if [ -z $TEMPLATE ]; then
    TEMPLATE=`ls $PREFIX-template.nii*`
fi
if [ -z $TEMPLATE ]; then
    echo "could not find template, exiting"
    exit 1
else
    echo "found template: $TEMPLATE"
fi

echo "sym : $DOSYMMETRY"
echo "fv : $DOFLIPVARIANCE" 

if [[ $TEMPLATE == *gz ]];
then
    echo "template is gzipped"
    gunzip -v $TEMPLATE
    TEMPLATE=`echo $TEMPLATE | sed 's/.gz//g'`
    echo "new template: $TEMPLATE"
fi


if [ $DOSYMMETRY ]; then
    echo "Estimating axis of symmetry"
    mkdir -p symmetry
    cd symmetry
    ln -s ../$TEMPLATE
    runSymmetryCan $TEMPLATE
    affineConv AFFINEAffine.txt
    cd ..
fi

flipXfm=`readlink -f symmetry/*Xfm.txt`
flipXfmTune=`readlink -f symmetry/AFFINEAffine.mat`

if [ $DOFLIPVARIANCE ]; then

    # check that sym directory exists, and exit with error if it does not
    if [ ! -d "symmetry" ]; then
        echo "No symmetry directory"
        exit 1
    fi

    echo "Estimating flip variance"

    ## Make list of relevant files
    if [ -f list_all_affine.txt ]; then
        echo "Using existing lists"
    else
        echo "Creating lists"
        genOutputListsCan "$PREFIX"
    fi

    ## Make directory and set up
    mkdir -p flipVariance
    cd flipVariance
    ln -s ../list*txt .
    
    tmp=`echo $TEMPLATE | sed 's/.nii/.tif/g'` 
    echo "tmp: $tmp"
    templateTif=`readlink -f ../symmetry/$tmp`
    echo "template tif: $templateTif"

    ## Build ans submit qsub jobs to compute pixelwise distance
    executeRemote 'login2.int.janelia.org' "$flipVarianceScript $templateTif"

    analysisJobs=""    
    if [ $DORAYLEIGH ]; then
        echo "rayleigh"

        echo "#!/bin/bash" > rayJob.sh
        echo "perWindowRayleigh -q 4 -o $basedir/flipVariance/rayleigh.tif " `pwd`/*dist.tif >> rayJob.sh
        analysisJobs="$analysisJobs rayJob.sh"
    fi

    if [ $DOCENTILES ]; then
        echo "centiles"
        echo "#!/bin/bash" > centileJob.sh
        echo "perWindowCentile -q 4 -c $CENTILE_OPTS -o $basedir/flipVariance/dist_centiles_0-10-50-90-100.tif " `pwd`/*dist.tif >> centileJob.sh
        analysisJobs="$analysisJobs centileJob.sh"
    fi

    if [ $DOMEANVAR ]; then
        echo "mean and variance"
        echo "#!/bin/bash" > meanVarJob.sh
        echo "meanVar 4 $basedir/flipVariance/mnVar_" `pwd`/*dist.tif >> meanVarJob.sh
        analysisJobs="$analysisJobs meanVarJob.sh"
    fi

    if [ $DOHISTOGRAM ]; then
        echo "Computing histograms"
        echo $maskF
        genHistograms $templateTif
    fi

    echo $analysisJobs
    executeRemote 'login2.int.janelia.org' "submitJobsQsub 4 $analysisJobs"

    cd ..
fi
