#!/bin/bash
# For the record,
# ANTSJacobian uses log base e

#TODO expose doLog as optional parameter
doLog="1"

mkdir -p jacobian
cd jacobian
ln -s ../list_all_warp.txt .

for warpF in `cat list_all_warp.txt`
do
    out=`echo $warpF | sed 's/.nii/_logJac/g'`
    echo $warpF
    echo $out
    ANTSJacobian 3 $warpF $out $doLog
done

cd ..
